export type RoleName = 'MEMBER' | 'MODERATOR' | 'ADMIN' | 'SUPER_ADMIN';

export const PERMISSION_MATRIX: Record<RoleName, string[]> = {
  MEMBER: [
    'posts:read:published',
    'posts:create',
    'posts:update:own',
    'posts:delete:own',
    'comments:create',
    'comments:delete:own',
    'reactions:create',
    'follows:create',
    'reports:create',
  ],
  MODERATOR: [
    'posts:read:published',
    'posts:create',
    'posts:update:own',
    'posts:delete:own',
    'posts:delete:any',
    'comments:create',
    'comments:delete:own',
    'comments:delete:any',
    'reactions:create',
    'follows:create',
    'reports:create',
    'reports:review',
    'moderation:action',
  ],
  ADMIN: [
    'posts:read:published',
    'posts:create',
    'posts:update:own',
    'posts:delete:own',
    'posts:delete:any',
    'comments:create',
    'comments:delete:own',
    'comments:delete:any',
    'reactions:create',
    'follows:create',
    'reports:create',
    'reports:review',
    'moderation:action',
    'categories:manage',
    'tags:manage',
    'users:suspend',
    'users:ban',
    'audit_logs:read',
  ],
  SUPER_ADMIN: [
    'posts:read:published',
    'posts:create',
    'posts:update:own',
    'posts:delete:own',
    'posts:delete:any',
    'comments:create',
    'comments:delete:own',
    'comments:delete:any',
    'reactions:create',
    'follows:create',
    'reports:create',
    'reports:review',
    'moderation:action',
    'categories:manage',
    'tags:manage',
    'users:suspend',
    'users:ban',
    'users:assign_role',
    'audit_logs:read',
  ],
};
