'use client';
import React, { useState } from 'react';
import { Plus, Eye, Pencil, Trash2, FileText, X } from 'lucide-react';
import { useModerationPosts } from '@/lib/moderation/use-post-moderation';
import { useDeletePostFromAdmin, useUpdatePost } from '@/lib/posts/use-post-mutations';
import { ModerationPostItem } from '@/types/moderation';
import { AdminPagination } from './AdminPagination';
import { AdminSearchInput } from './AdminSearchInput';
import { AdminCreatePostModal } from './AdminCreatePostModal';
import { CoverImagePicker, registerCoverPreview } from '@/components/media/CoverImagePicker';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';
import { useToast } from '@/lib/toast/ToastContext';
import { resolveMediaUrl } from '@/lib/utils/media';

type EditablePost = ModerationPostItem & { body?: string | null };
const fallbackCover = 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=320&h=220&auto=format&fit=crop&q=80';

export function AdminPostsTable() {
  const { toast } = useToast(); const [page, setPage] = useState(1); const [selected, setSelected] = useState<EditablePost|null>(null); const [mode, setMode] = useState<'view'|'edit'|'delete'|null>(null); const [createOpen, setCreateOpen] = useState(false); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [coverMediaId, setCoverMediaId] = useState<string|null>(null); const [search, setSearch] = useState(''); const [contentFilter, setContentFilter] = useState('SERIES'); const [statusFilter, setStatusFilter] = useState('ALL'); const [moderationFilter, setModerationFilter] = useState('ALL');
  const { data, isLoading, isError, refetch } = useModerationPosts({ moderationStatus: 'ALL', page, limit: 15 }); const deleteMutation = useDeletePostFromAdmin(); const updateMutation = useUpdatePost(selected?.id ?? ''); const posts = data?.data ?? []; const meta = data?.meta ?? { page: 1, limit: 15, totalItems: 0, totalPages: 0, hasNextPage: false, hasPreviousPage: false };
  const filtered = posts.filter(p => { const q = search.trim().toLowerCase(); return p.contentType === 'SERIES' && (!q || `${p.title} ${p.slug} ${p.author?.username ?? ''}`.toLowerCase().includes(q)) && (contentFilter === 'ALL' || p.contentType === contentFilter) && (statusFilter === 'ALL' || p.status === statusFilter) && (moderationFilter === 'ALL' || p.moderationStatus === moderationFilter); });
  const open = (post: ModerationPostItem, next: 'view'|'edit'|'delete') => { const item = post as EditablePost; registerCoverPreview(item.coverMedia?.id, resolveMediaUrl(item.coverMedia?.secureUrl || item.coverMedia?.id, fallbackCover)); setSelected(item); setMode(next); setTitle(item.title); setBody(item.body ?? ''); setCoverMediaId(item.coverMedia?.id ?? null); };
  const close = () => { if (!deleteMutation.isPending && !updateMutation.isPending) { setSelected(null); setMode(null); } };
  const remove = async () => { if (!selected) return; try { await deleteMutation.mutateAsync(selected.id); toast.success('Đã xóa mềm bài viết.'); close(); await refetch(); } catch (e: any) { toast.error(e?.response?.data?.message || 'Không thể xóa bài viết.'); } };
  const update = async (e: React.FormEvent) => { e.preventDefault(); if (!selected || !title.trim()) return; try { await updateMutation.mutateAsync({ title: title.trim(), body: body.trim() || undefined, coverMediaId: coverMediaId || undefined }); toast.success('Đã cập nhật bài viết.'); close(); await refetch(); } catch (err: any) { toast.error(err?.response?.data?.message || 'Không thể cập nhật bài viết.'); } };
  const badge = (value: string) => <Badge variant={value === 'APPROVED' || value === 'PUBLISHED' ? 'success' : value === 'BANNED' || value === 'HIDDEN' ? 'danger' : value === 'NEWS' ? 'warning' : 'default'}>{value}</Badge>;
  return <div className="space-y-6"><div className="flex flex-col gap-4 border-b border-border pb-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><div className="rounded-lg bg-primary/10 p-2 text-primary"><FileText className="h-5 w-5" /></div><div><h1 className="font-heading text-xl font-bold">Quản lý bài viết</h1><p className="mt-1 text-xs text-muted-foreground">Danh sách toàn bộ bài viết và các thao tác quản trị nội dung.</p></div></div><Button size="sm" onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4" />Thêm bài viết</Button></div>
    <div className="flex flex-col gap-3 rounded-xl border border-border bg-surface/70 p-3 lg:flex-row lg:items-center lg:justify-between"><AdminSearchInput value={search} onValueChange={v => { setSearch(v); setPage(1); }} placeholder="Tìm theo tiêu đề, slug hoặc tác giả..." aria-label="Tìm kiếm bài viết" /><div className="flex flex-wrap gap-2"><select value={contentFilter} onChange={e => setContentFilter(e.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-xs"><option value="ALL">Tất cả loại</option><option value="COMMUNITY">COMMUNITY</option><option value="SERIES">SERIES</option><option value="NEWS">NEWS</option></select><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-xs"><option value="ALL">Tất cả trạng thái</option><option value="DRAFT">DRAFT</option><option value="PUBLISHED">PUBLISHED</option><option value="HIDDEN">HIDDEN</option><option value="ARCHIVED">ARCHIVED</option></select><select value={moderationFilter} onChange={e => setModerationFilter(e.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-xs"><option value="ALL">Tất cả kiểm duyệt</option><option value="UNREVIEWED">UNREVIEWED</option><option value="APPROVED">APPROVED</option><option value="BANNED">BANNED</option></select><Button variant="outline" size="sm" onClick={() => void refetch()}>Làm mới</Button></div></div>
    <div className="overflow-hidden rounded-xl border border-border bg-surface"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-border bg-muted/50 font-mono uppercase text-muted-foreground"><tr><th className="px-4 py-3">Bài viết</th><th className="px-4 py-3">Tác giả</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Ngày đăng</th><th className="px-4 py-3 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-border">{isLoading ? <tr><td colSpan={5} className="py-12 text-center">Đang tải bài viết...</td></tr> : isError ? <tr><td colSpan={5} className="py-12 text-center text-danger">Không thể tải bài viết.</td></tr> : filtered.length === 0 ? <tr><td colSpan={5} className="py-12 text-center">Không có bài viết phù hợp.</td></tr> : filtered.map(post => <tr key={post.id} className="hover:bg-muted/20"><td className="px-4 py-3"><div className="flex items-center gap-3"><img src={resolveMediaUrl(post.coverMedia?.secureUrl, fallbackCover)} alt="" className="h-10 w-14 rounded-md object-cover" /><div className="min-w-0"><p className="truncate font-semibold">{post.title}</p><p className="truncate font-mono text-xs text-muted-foreground">{post.slug}</p><div className="mt-1 flex gap-1">{badge(post.contentType)}{badge(post.status)}</div></div></div></td><td className="px-4 py-3 font-mono">{post.author?.username || post.authorId.slice(0, 8)}</td><td className="px-4 py-3">{badge(post.moderationStatus)}</td><td className="whitespace-nowrap px-4 py-3 text-muted-foreground">{new Date(post.publishedAt || post.createdAt).toLocaleString('vi-VN')}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => open(post, 'view')} title="Xem"><Eye className="h-4 w-4" /></Button><Button variant="outline" size="sm" onClick={() => open(post, 'edit')} title="Sửa"><Pencil className="h-4 w-4" /></Button><Button variant="outline" size="sm" onClick={() => open(post, 'delete')} title="Xóa" className="text-danger"><Trash2 className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div><AdminPagination meta={meta} itemLabel="bài viết" pageLabel="Trang" onPageChange={setPage} /></div>
    <AdminCreatePostModal open={createOpen} onClose={() => setCreateOpen(false)} onCreated={async () => { await refetch(); }} />
    {selected && mode && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-3xl rounded-2xl border border-border bg-surface shadow-2xl"><div className="flex items-center justify-between border-b border-border p-5"><h2 className="font-heading text-lg font-bold">{mode === 'view' ? 'Xem bài viết' : mode === 'edit' ? 'Sửa bài viết' : 'Xóa bài viết'}</h2><button type="button" onClick={close} aria-label="Đóng"><X className="h-5 w-5" /></button></div>{mode === 'view' && <div className="max-h-[65vh] space-y-4 overflow-y-auto p-5"><img src={resolveMediaUrl(selected.coverMedia?.secureUrl || selected.coverMedia?.id, fallbackCover)} alt="" className="max-h-80 w-full rounded-xl border border-border object-contain" /><h3 className="text-xl font-bold">{selected.title}</h3><div className="whitespace-pre-wrap text-sm text-muted-foreground">{selected.body || 'Nội dung bài viết chưa được tải.'}</div></div>}{mode === 'edit' && <form onSubmit={update} className="max-h-[80vh] space-y-4 overflow-y-auto p-5"><CoverImagePicker value={coverMediaId} fallbackPreviewUrl={resolveMediaUrl(selected.coverMedia?.secureUrl || selected.coverMedia?.id, fallbackCover)} onChange={setCoverMediaId} /><label className="block text-xs font-semibold">Tiêu đề<input value={title} onChange={e => setTitle(e.target.value)} className="mt-2 w-full rounded-md border border-input bg-background p-2.5 text-sm" /></label><label className="block text-xs font-semibold">Nội dung<textarea value={body} onChange={e => setBody(e.target.value)} rows={10} className="mt-2 w-full rounded-md border border-input bg-background p-2.5 text-sm" /></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Hủy</Button><Button type="submit" isLoading={updateMutation.isPending}>Lưu thay đổi</Button></div></form>}{mode === 'delete' && <div className="space-y-5 p-5"><p className="text-sm text-muted-foreground">Bạn có chắc muốn xóa mềm bài viết <strong>“{selected.title}”</strong>?</p><div className="flex justify-end gap-2"><Button variant="outline" onClick={close}>Hủy</Button><Button variant="destructive" onClick={() => void remove()} isLoading={deleteMutation.isPending}>Xóa bài viết</Button></div></div>}</div></div>}</div>;
}
