'use client';
import { useEffect, useState } from 'react';
import { ChevronDown, Loader2, RefreshCw } from 'lucide-react';
import { learningAdminService } from '@/lib/learning/learning-admin-service';
import type { EditorialStatus, LearningAdminPost } from '@/types/learning-admin';
const statuses: Array<{ value: EditorialStatus; label: string }> = [{ value: 'DRAFT', label: 'Bản nháp' }, { value: 'REVIEW', label: 'Chờ duyệt' }, { value: 'PUBLISHED', label: 'Đã xuất bản' }, { value: 'NEEDS_UPDATE', label: 'Cần cập nhật' }, { value: 'ARCHIVED', label: 'Lưu trữ' }];
export function LearningEditorialQueue() {
  const [filter, setFilter] = useState<EditorialStatus>('REVIEW'); const [posts, setPosts] = useState<LearningAdminPost[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null);
  async function load() { setLoading(true); try { setPosts((await learningAdminService.getPosts(filter)).data); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [filter]);
  async function changeStatus(id: string, status: EditorialStatus) { setSaving(id); try { await learningAdminService.updateStatus(id, status); await load(); } finally { setSaving(null); } }
  return <section className="space-y-5"><header className="flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-mono uppercase tracking-[.18em] text-primary">Learning editorial</p><h1 className="mt-2 text-3xl font-bold">Duyệt nội dung học tập</h1><p className="mt-1 text-sm text-muted-foreground">Kiểm tra và chuyển trạng thái bài học trước khi xuất bản.</p></div><button type="button" onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm font-semibold"><RefreshCw className="h-4 w-4" />Làm mới</button></header><div className="flex flex-wrap gap-2">{statuses.map((status) => <button key={status.value} type="button" onClick={() => setFilter(status.value)} className={`min-h-10 rounded-full border px-4 text-sm font-semibold ${filter === status.value ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-surface hover:border-primary'}`}>{status.label}</button>)}</div>{loading ? <div className="flex items-center gap-2 rounded-2xl border border-border p-8 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />Đang tải bài học…</div> : <div className="overflow-hidden rounded-2xl border border-border bg-surface">{posts.length === 0 ? <p className="p-10 text-center text-sm text-muted-foreground">Không có bài học ở trạng thái này.</p> : <div className="divide-y divide-border">{posts.map((post) => <article key={post.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><h2 className="truncate font-semibold">{post.title}</h2><p className="mt-1 text-xs text-muted-foreground">Cập nhật {new Date(post.updatedAt).toLocaleDateString('vi-VN')} · {post.slug}</p></div><div className="relative shrink-0"><select value={post.editorialStatus} disabled={saving === post.id} onChange={(event) => void changeStatus(post.id, event.target.value as EditorialStatus)} className="min-h-11 appearance-none rounded-xl border border-border bg-surface py-2 pl-4 pr-10 text-sm font-semibold"><option value="DRAFT">Bản nháp</option><option value="REVIEW">Chờ duyệt</option><option value="PUBLISHED">Đã xuất bản</option><option value="NEEDS_UPDATE">Cần cập nhật</option><option value="ARCHIVED">Lưu trữ</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-4 w-4" /></div></article>)}</div>}</div>}</section>;
}
