import { PostEntity } from '@/types/content';

export const DEMO_FEATURED_POSTS: PostEntity[] = [
  {
    id: 'demo-post-1',
    authorId: '987fcdeb-51a2-43f7-9abc-1234567890ab',
    contentType: 'COMMUNITY',
    title: 'Financial Analysis and Market Intelligence',
    slug: 'financial-analysis-market-intelligence',
    body: 'Comprehensive breakdown of macroeconomic trends, quantitative valuation models, and equity research.',
    coverMediaId: null,
    categoryId: 'cat-macro',
    status: 'PUBLISHED',
    metaTitle: 'Financial Analysis and Market Intelligence',
    metaDescription: 'Meta description excerpt tit amet, consectetur adipiscing elit. Restams store promotion and convenience hosts to export a notta line more.',
    viewCount: 1200,
    publishedAt: '2023-08-17T14:30:00Z',
    createdAt: '2023-08-17T10:00:00Z',
    updatedAt: '2023-08-17T14:30:00Z',
    deletedAt: null,
  },
  {
    id: 'demo-post-2',
    authorId: '12345678-51a2-43f7-9abc-1234567890cd',
    contentType: 'SERIES',
    title: 'Financial Analysis Pulls & Market Intelligence',
    slug: 'financial-analysis-pulls-market-intelligence',
    body: 'Deep dive into market structure, liquidity flows, and quantitative options strategies.',
    coverMediaId: null,
    categoryId: 'cat-equities',
    status: 'PUBLISHED',
    metaTitle: 'Financial Analysis Pulls & Market Intelligence',
    metaDescription: 'Meta description excerpt tit amet, consectetur adipiscing elit. Restams store promotion and convenience hosts to export a notta line more.',
    viewCount: 30000,
    publishedAt: '2023-08-17T14:30:00Z',
    createdAt: '2023-08-17T10:00:00Z',
    updatedAt: '2023-08-17T14:30:00Z',
    deletedAt: null,
  },
  {
    id: 'demo-post-3',
    authorId: '55556666-51a2-43f7-9abc-1234567890ef',
    contentType: 'COMMUNITY',
    title: 'Fixed Income Multiples & Monetary Policy Shift',
    slug: 'fixed-income-multiples-monetary-policy-shift',
    body: 'Analyzing treasury spread widening and institutional asset allocation models.',
    coverMediaId: null,
    categoryId: 'cat-macro',
    status: 'PUBLISHED',
    metaTitle: 'Fixed Income Multiples',
    metaDescription: 'Comprehensive breakdown of historical treasury yield curve dynamics and central bank liquidity operations.',
    viewCount: 8500,
    publishedAt: '2023-08-15T09:00:00Z',
    createdAt: '2023-08-15T09:00:00Z',
    updatedAt: '2023-08-15T09:00:00Z',
    deletedAt: null,
  },
];
