'use client';

import { useMemo, useState } from 'react';
import { Info, TrendingUp } from 'lucide-react';
import { AppShell } from '@/components/layout/AppShell';

const money = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(Math.max(0, value));
const number = (value: number) => new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 0 }).format(Math.max(0, value));
const field = (label: string, value: number, setValue: (value: number) => void, suffix = '₫') => <label className="space-y-1.5 text-sm font-semibold">{label}<div className="flex items-center rounded-xl border border-border bg-background px-3"><input type="number" min="0" value={value} onChange={(e) => setValue(Number(e.target.value) || 0)} className="h-11 min-w-0 flex-1 bg-transparent outline-none" />{suffix && <span className="text-xs text-muted-foreground">{suffix}</span>}</div></label>;

function GrowthChart({ values }: { values: number[] }) {
  const max = Math.max(...values, 1);
  return <div className="flex h-44 items-end gap-1 rounded-xl bg-muted/30 p-4">{values.map((value, index) => <div key={index} title={`Năm ${index + 1}: ${money(value)}`} className="group relative flex-1 rounded-t-md bg-primary/70 transition-all hover:bg-primary" style={{ height: `${Math.max(4, value / max * 100)}%` }} />)}</div>;
}

export default function ToolsPage() {
  const [initial, setInitial] = useState(100000000); const [monthly, setMonthly] = useState(5000000); const [rate, setRate] = useState(10); const [years, setYears] = useState(10);
  const [price, setPrice] = useState(100000); const [eps, setEps] = useState(10000); const [pe, setPe] = useState(12);
  const [dividend, setDividend] = useState(5000); const [growth, setGrowth] = useState(5); const [required, setRequired] = useState(12);
  const growthData = useMemo(() => Array.from({ length: years }, (_, i) => initial * Math.pow(1 + rate / 1200, (i + 1) * 12) + monthly * ((Math.pow(1 + rate / 1200, (i + 1) * 12) - 1) / (rate / 1200 || 1))), [initial, monthly, rate, years]);
  const future = growthData.at(-1) || 0; const invested = initial + monthly * years * 12;
  const peValue = eps * pe; const gordonValue = required > growth ? dividend * (1 + growth / 100) / ((required - growth) / 100) : 0;
  return <AppShell showRightSidebar={false}><main className="mx-auto max-w-5xl space-y-8 py-2"><header><p className="font-mono text-xs uppercase tracking-[.18em] text-primary">Finance tools</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Công cụ tài chính tương tác</h1><p className="mt-2 max-w-2xl text-muted-foreground">Tự kiểm tra các kịch bản tích lũy và định giá cơ bản ngay trên trình duyệt.</p></header>
    <section className="rounded-2xl border border-border bg-surface p-5 shadow-xs sm:p-7"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-primary/10 p-2 text-primary"><TrendingUp className="h-5 w-5" /></div><div><h2 className="text-xl font-bold">Lãi kép & kế hoạch tích lũy</h2><p className="text-sm text-muted-foreground">Ước tính giá trị danh mục theo thời gian.</p></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{field('Vốn ban đầu', initial, setInitial)}{field('Tích lũy mỗi tháng', monthly, setMonthly)}{field('Lãi suất kỳ vọng', rate, setRate, '%/năm')}{field('Thời gian', years, setYears, 'năm')}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.4fr]"><div className="rounded-xl bg-primary p-5 text-primary-foreground"><p className="text-sm opacity-80">Giá trị dự kiến</p><p className="mt-1 text-3xl font-bold">{money(future)}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="opacity-70">Tổng vốn góp</p><strong>{money(invested)}</strong></div><div><p className="opacity-70">Tiền lãi</p><strong>{money(future - invested)}</strong></div></div></div><GrowthChart values={growthData} /></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-surface p-5 shadow-xs sm:p-7"><h2 className="text-xl font-bold">Định giá theo P/E</h2><p className="mt-1 text-sm text-muted-foreground">Giá hợp lý = EPS × P/E mục tiêu.</p><div className="mt-5 space-y-4">{field('EPS dự phóng', eps, setEps)}{field('P/E mục tiêu', pe, setPe, 'lần')}</div><div className="mt-5 rounded-xl bg-muted/40 p-4"><p className="text-sm text-muted-foreground">Giá trị ước tính</p><p className="mt-1 text-2xl font-bold text-primary">{money(peValue)}</p><p className="mt-2 text-xs">Giá hiện tại: {money(price)} · Biên an toàn: {peValue ? `${number((1 - price / peValue) * 100)}%` : '—'}</p></div></section><section className="rounded-2xl border border-border bg-surface p-5 shadow-xs sm:p-7"><h2 className="text-xl font-bold">Mô hình Gordon Growth</h2><p className="mt-1 text-sm text-muted-foreground">Định giá cổ phiếu dựa trên cổ tức tăng trưởng ổn định.</p><div className="mt-5 space-y-4">{field('Cổ tức năm tới', dividend, setDividend)}{field('Tăng trưởng dài hạn', growth, setGrowth, '%/năm')}{field('Tỷ suất sinh lời yêu cầu', required, setRequired, '%/năm')}</div><div className="mt-5 rounded-xl bg-muted/40 p-4"><p className="text-sm text-muted-foreground">Giá trị ước tính</p><p className="mt-1 text-2xl font-bold text-primary">{gordonValue ? money(gordonValue) : 'Không hợp lệ'}</p><p className="mt-2 text-xs">Tỷ suất yêu cầu phải lớn hơn tốc độ tăng trưởng.</p></div></section></div>
    <div className="flex items-start gap-2 rounded-xl border border-amber-300/60 bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><Info className="mt-0.5 h-4 w-4 shrink-0" />Các kết quả chỉ mang tính minh họa, không phải khuyến nghị đầu tư.</div></main></AppShell>;
}
