/**
 * Synchronized Business Error Codes for Finance Community Web Client.
 * Corresponds to Backend ErrorCode enum.
 */
export enum ErrorCode {
  // Authentication & Session
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_ACCOUNT_BANNED = 'AUTH_ACCOUNT_BANNED',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_DEACTIVATED = 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // Posts & Content Management
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_SLUG_DUPLICATED = 'POST_SLUG_DUPLICATED',
  POST_FORBIDDEN_ACTION = 'POST_FORBIDDEN_ACTION',
  POST_INVALID_STATUS = 'POST_INVALID_STATUS',
  POST_NOT_PUBLISHED = 'POST_NOT_PUBLISHED',

  // Comments & Discussions
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_DEPTH_EXCEEDED = 'COMMENT_DEPTH_EXCEEDED',
  COMMENT_LOCKED = 'COMMENT_LOCKED',
  COMMENT_FORBIDDEN_ACTION = 'COMMENT_FORBIDDEN_ACTION',

  // Categories & Tags
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_DUPLICATED = 'CATEGORY_SLUG_DUPLICATED',
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',
  TAG_SLUG_DUPLICATED = 'TAG_SLUG_DUPLICATED',

  // Media & Assets
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  MEDIA_INVALID_FORMAT = 'MEDIA_INVALID_FORMAT',
  MEDIA_FILE_TOO_LARGE = 'MEDIA_FILE_TOO_LARGE',

  // Moderation & Governance
  MODERATION_ACTION_FAILED = 'MODERATION_ACTION_FAILED',
  REPORT_ALREADY_EXISTS = 'REPORT_ALREADY_EXISTS',
  REPORT_NOT_FOUND = 'REPORT_NOT_FOUND',

  // System, Rate Limiting & Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DATABASE_ERROR = 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
