'use client';
import { useEffect, useState } from 'react';
import { Loader2, Plus, Save, Trash2 } from 'lucide-react';
import { apiClient } from '@/lib/api/client';
type Option = { id: string; label: string; isCorrect: boolean };
type Question = { prompt: string; options: Option[]; explanation: string; };
const blank = (): Question => ({ prompt: '', explanation: '', options: [{ id: crypto.randomUUID(), label: '', isCorrect: true }, { id: crypto.randomUUID(), label: '', isCorrect: false }] });
export function LearningQuizManager({ postId }: { postId: string }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [questions, setQuestions] = useState<Question[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { let active = true; void apiClient.get(`/learning/admin/posts/${postId}/quiz`).then(({ data }) => { if (!active || !data.quiz) return; setTitle(data.quiz.title); setDescription(data.quiz.description || ''); setQuestions(data.questions.map((q: any) => ({ prompt: q.prompt, explanation: q.explanation || '', options: q.options.map((o: any) => ({ id: o.id, label: o.label || o.text || '', isCorrect: Boolean(o.isCorrect) })) }))); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [postId]);
  function updateQuestion(index: number, patch: Partial<Question>) { setQuestions((current) => current.map((q, i) => i === index ? { ...q, ...patch } : q)); }
  async function save() { if (!title.trim() || questions.some((q) => !q.prompt.trim() || q.options.length < 2)) return; setSaving(true); setMessage(''); try { await apiClient.patch(`/learning/admin/posts/${postId}/quiz`, { title: title.trim(), description: description.trim() || undefined, questions }); setMessage('Đã lưu quiz.'); } catch { setMessage('Không thể lưu quiz.'); } finally { setSaving(false); } }
  if (loading) return <div className="flex items-center gap-2 rounded-2xl border border-border p-5 text-sm"><Loader2 className="h-4 w-4 animate-spin" />Đang tải quiz…</div>;
  return <section className="space-y-5 rounded-2xl border border-border bg-muted/20 p-5"><div><h2 className="text-lg font-bold">Quiz bài học</h2><p className="mt-1 text-sm text-muted-foreground">Tạo câu hỏi để người học tự kiểm tra kiến thức.</p></div><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Tiêu đề quiz" className="min-h-11 w-full rounded-xl border border-border bg-surface px-3 text-sm" /><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Mô tả ngắn (không bắt buộc)" className="min-h-20 w-full rounded-xl border border-border bg-surface p-3 text-sm" />{questions.map((question, qi) => <div key={qi} className="space-y-3 rounded-xl border border-border bg-surface p-4"><div className="flex gap-3"><input value={question.prompt} onChange={(e) => updateQuestion(qi, { prompt: e.target.value })} placeholder={`Câu hỏi ${qi + 1}`} className="min-h-11 flex-1 rounded-lg border border-border px-3 text-sm" /><button type="button" onClick={() => setQuestions((current) => current.filter((_, i) => i !== qi))} aria-label="Xóa câu hỏi" className="p-2 text-destructive"><Trash2 className="h-4 w-4" /></button></div>{question.options.map((option, oi) => <div key={option.id} className="flex items-center gap-2"><input type="radio" name={`correct-${qi}`} checked={option.isCorrect} onChange={() => updateQuestion(qi, { options: question.options.map((o, i) => ({ ...o, isCorrect: i === oi })) })} aria-label="Đáp án đúng" /><input value={option.label} onChange={(e) => updateQuestion(qi, { options: question.options.map((o, i) => i === oi ? { ...o, label: e.target.value } : o) })} placeholder={`Lựa chọn ${oi + 1}`} className="min-h-10 flex-1 rounded-lg border border-border px-3 text-sm" /></div>)}<textarea value={question.explanation} onChange={(e) => updateQuestion(qi, { explanation: e.target.value })} placeholder="Giải thích đáp án" className="min-h-16 w-full rounded-lg border border-border p-3 text-sm" /></div>)}<div className="flex flex-wrap gap-3"><button type="button" onClick={() => setQuestions((current) => [...current, blank()])} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm font-semibold"><Plus className="h-4 w-4" />Thêm câu hỏi</button><button type="button" disabled={saving || !title.trim()} onClick={() => void save()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-60"><Save className="h-4 w-4" />{saving ? 'Đang lưu…' : 'Lưu quiz'}</button>{message && <span className="self-center text-sm text-muted-foreground">{message}</span>}</div></section>;
}
