'use client';
import { FormEvent, useEffect, useState } from 'react';
import { ExternalLink, Loader2, Plus, Trash2 } from 'lucide-react';
import { apiClient } from '@/lib/api/client';

type Source = { id: string; title: string; url: string; publisher: string | null; checkedAt: string | null };
export function LearningSourceManager({ postId }: { postId: string }) {
  const [sources, setSources] = useState<Source[]>([]); const [title, setTitle] = useState(''); const [url, setUrl] = useState(''); const [publisher, setPublisher] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); try { const r = await apiClient.get<Source[]>(`/learning/posts/${postId}/sources`); setSources(r.data); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [postId]);
  async function add(event: FormEvent) { event.preventDefault(); if (!title.trim() || !url.trim()) return; setSaving(true); try { await apiClient.post(`/learning/admin/posts/${postId}/sources`, { title: title.trim(), url: url.trim(), publisher: publisher.trim() || undefined }); setTitle(''); setUrl(''); setPublisher(''); await load(); } finally { setSaving(false); } }
  async function remove(id: string) { await apiClient.delete(`/learning/admin/sources/${id}`); setSources((current) => current.filter((source) => source.id !== id)); }
  return <section className="space-y-4 rounded-2xl border border-border bg-muted/20 p-5"><h2 className="text-lg font-bold">Nguồn tham khảo</h2><form onSubmit={add} className="grid gap-3 sm:grid-cols-2"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Tên tài liệu / bài viết" className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm" required /><input value={url} onChange={(e) => setUrl(e.target.value)} type="url" placeholder="https://..." className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm" required /><input value={publisher} onChange={(e) => setPublisher(e.target.value)} placeholder="Nhà xuất bản (không bắt buộc)" className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm" /><button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-60"><Plus className="h-4 w-4" />Thêm nguồn</button></form>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <div className="space-y-2">{sources.map((source) => <div key={source.id} className="flex items-center gap-3 rounded-xl border border-border bg-surface p-3 text-sm"><ExternalLink className="h-4 w-4 shrink-0 text-primary" /><a href={source.url} target="_blank" rel="noreferrer" className="min-w-0 flex-1 truncate hover:text-primary">{source.title}</a><button type="button" onClick={() => void remove(source.id)} aria-label={`Xóa nguồn ${source.title}`} className="p-2 text-destructive"><Trash2 className="h-4 w-4" /></button></div>)}{sources.length === 0 && <p className="text-sm text-muted-foreground">Chưa có nguồn tham khảo.</p>}</div>}</section>;
}
